openapi: 3.0.0

info:
  title: Spesifikasi Testing
  description: Digunakan untuk melakukan testing fitur dan performa Selvi Framework
  version: 1.0.0

components:
  securitySchemes:
    token:
      type: apiKey
      in: header
      name: Authorization

servers:
  - url: http://localhost:8091/mysql/
    description: MySQL Driver
  - url: http://localhost:8091/sqlsrv/
    description: SQLSrv Driver

tags:
  - name: Auth
    description: Mengelola autentikasi pengguna
  - name: Kontak
    description: Mengelola data kontak
  - name: Grup
    description: Mengelola data Grup
  - name: Produk
    description: Mengelola data Produk
  - name: Transaksi
    description: Mengelola data Transaksi

paths:
  /auth:
    $ref: './paths/Auth/Auth.yaml'
    
  /kontak:
    $ref: './paths/Kontak/Kontak.yaml'
  /kontak/{idKontak}:
    $ref: './paths/Kontak/Kontak-{idKontak}.yaml'

  /grup:
    $ref: './paths/Grup/Grup.yaml'
  /grup/{idGrup} :
    $ref: './paths/Grup/Grup-{idGrup}.yaml'

  /produk:
    $ref: './paths/Produk/Produk.yaml'
  /produk/{idProduk}:
    $ref: './paths/Produk/Produk-{idProduk}.yaml'

  /transaksi:
    $ref: './paths/Transaksi/Transaksi.yaml'
  /transaksi/{idTransaksi}:
    $ref: './paths/Transaksi/Transaksi-{idTransaksi}.yaml'
