version: '3.0'
name: selvi_framework
services:
  backend: 
    container_name: selvi_framework_container
    image: mochrira/dev:latest
    volumes:
      - ./:/workspace/www
      - ../src:/workspace/src
    ports:
      - 8091:80
    networks:
      - database

networks:
  database: 
    name: database
    external: true