version: '3.0'
name: selvi_framework
services:
  backend: 
    container_name: selvi_framework_container
    image: rsyasmin/dev:latest
    volumes:
      - ./src:/workspace/www
      - ../src:/workspace/src
    ports:
      - 8091:80
    networks:
      - environment
      - database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.framework.rule=Host(`framework.local`)"
      - "traefik.http.services.framework.loadbalancer.server.port=80"

networks:
  environment:
    name: environment
    external: true

  database:
    name: database
    external: true